var input = [
   "Emerging Technologies as a Chance & the Importance of the Human Factor",
   "Bubble Making Workshop for Kids (2)",
   "Dext Science Kits – Empower Playgrounds",
   "Cambridge Analytica and data exploitation – a critical intervention",
   "Medical supplies in emergencies – testing the 3D prints",
   "Citizen Science and Environmental Data: Why Everybody beats Anybody",
   "Information in the Digital Age: Trust, Diversity and the Future of Search",
   "Meetup: Accelerating Human Rights Investigations with Computer Vision",
   "Algorithms of Oppression",
   "Forensic Architecture – Data against Devilry",
   "\"Whack\"athon: Co-create a Soundtrack of the Cubicle Ages",
   "Creative technology workshop – Explore movement and make the future!",
   "Emergency Boxes",
   "Airdrop",
   "Beyond Recognition: Cyberspace’s past, present and future",
   "Eco-Making: Ecologically Sustainable Hardware Design Meetup",
   "Hardware for Health & Wellbeing: Introducing Careables",
   "Hacking the Ivory Tower: Towards Lab Equipment as a Common Good",
   "Crisis Response Makerspaces",
   "Mensch und Maschine – wer programmiert wen?",
   "Creating new business models and accelerate innovation: Daimlers API platform",
   "Let’s do ”something” with Blockchain",
   "When Algorithms are your Boss: Staying Human in Platform-Mediated Work",
   "Bubble Making Workshop for Kids",
   "Data Responsibility on the Front Lines: Protection and Security in Humanitarian Response",
   "How the unconnected are connecting themselves",
   "The new energy paradigm",
   "99 ganz legale Netzbastel-Tricks",
   "Exploring The Cultural Divide Between Science And The Humanities",
   "The New Frontiers of Technology and Impact",
   "Systems of Biometric Control",
   "The end for freedom of thought? On the commercial use of big brain data",
   "Make your own bio plastic",
   "Make your feminist light patch!",
   "When Spies Come Home: Inside the Consumer Spyware Industry",
   "SolarBox. build your Open Source mobile and modular solar power unit",
   "Make open climate data work",
   "The Solution for Loneliness – The Abandonment of Our Next Frontiers",
   "Kryptopia oder altes Geld mit neuen Mitteln: Bauen wir noch ein neues Finanzsystem – oder passen wir das alte nur an?",
   "Low poly dreams creation (Pepakura Designer software)",
   "Governing the Internet Infrastructure as a Commons",
   "Who will control Big Data, the currency of the digital age?",
   "Detecting Illegal Small Scale Mines in Ghana using Deep Learning",
   "Doctor, Doctor, Where is my Digital Diagnosis?",
   "Hear How You Like To Hear",
   "Spatial Computing – VR & AR als Grundlagen für eine neue Computer-Ära",
   "Coding Performance: Algorithms & Rituals",
   "The Web needs a voice – literally, technically, politically",
   "VR stellt unseren Begriff vom echten Leben in Frage",
   "The Internet of shitty Things goes POP",
   "Robots behaving badly: legal responsibility in the age of artificial intelligence",
   "Code+Design",
   "Domain of One's Own: Reclaim Your Data Meetup",
   "Opening Keynote: How an Algorithmic World Can Be Undermined",
   "The gendered shaping of Workplace Technology",
   "Startklar?! – Wie verändert sich Bildung in einer digitalisierten Gesellschaft",
   "She*fix! – A feminist online channel for tech tutorials (3)",
   "She*fix! – A feminist youtube channel for tech tutorials (2)",
   "She*fix! – A feminist youtube channel for tech tutorials (1)",
   "A failure of imagination and the rise of enhanced cognition as a human right",
   "Crafting the Future – VOC-force for tomorrow",
   "Lehren & Lernen unterwegs Meetup",
   "Citizen Science Networks Meetup",
   "Domain of One's Own: Reclaim Your Data",
   "re:learn Lightning Talks Meetup",
   "re:learn Lightning Talks",
   "Fanclub Öffentliche Bibliotheken",
   "Ten Directions to Move Open Education Forward – CPT+10",
   "Können Programme Wälder verwalten und die Natur schützen?",
   "Die Möglichkeit einer Lüge: Was wir von den Erfindern der Holocaustleugnung über Fake News lernen können",
   "Trust us – your health data are safe ... oops.",
   "Exploring the micro universe: examine the critters surrounding you!",
   "Youth skills for the future of work(less) on the global south",
   "RoboRace für Kinder ab 7 Jahren",
   "Können Making, Open Source und Design die Schule von morgen inspirieren?",
   "Digitale Bildung für Kinder selbermachen mit den Coderdojos",
   "Unterrichten mit Mini-Computern: Fallbeispiel Raspberry Pi",
   "Maker Education: experiences from schools and beyond",
   "#ASKotec: an emergeny field kit for Access to Skills and Knowledge",
   "Internet Research Meetup: Show Off Your Data!",
   "Endgegner Computerspiel",
   "Von YouTube lernen – Webvideos als Bildungs- und Informationsquelle",
   "Education 3.0: Sind YouTuber die besseren Lehrer?",
   "Do Robots and Digitisation really fit the demands of an ageing society?",
   "\"Plötzlich Wissen!\": Eine etwas andere Art der Wissenschaftskommunikation",
   "Filter Clash. Die große Gereiztheit der vernetzten Welt",
   "Lost Wisdom – Warum früher mehr Web war",
   "Medienpädagogisches Meetup",
   "What´s the name of the game? Von Streamer(inne)n, Monetarisierung und Verantwortung",
   "#AkwaabaX: Pop Culture and Urban Digital Society in Africa",
   "42. warum wir nach fragen, nicht nur nach antworten suchen müssen",
   "Männliche Verhütung geht Viral",
   "Vom Instagram-Hippie zum echten Öko-Aktivisten mit Zero Waste",
   "Embodiment of Digital Time",
   "Mate Circles & Workshops – Come & connect with many Mates",
   "Oh no, Cupid: Wieso dein Tinderwunsch bisher nicht in Erfüllung gegangen ist",
   "Blind-Date im Schrebergarten",
   "Absurdist Incubator: Exploring the ethics of fulfilling dreams",
   "Netzgemeindefest, Part 2",
   "1st Level Completed: Physical eSports",
   "The #future will be genius, #Europe! But how do we get there?",
   "Thessaloniki: An emerging (It) destination Young – Creative – Innovative",
   "Ethik in Unternehmen: Maßnahmen der freiwilligen Selbstregulierung vs. Politische Regulierung",
   "rp goes USA",
   "Mit Apps gegen den Hunger",
   "Wie kommen Innovationen in das deutsche Gesundheitssystem?",
   "Digital Principles unpacked: Data, Ethics and Open Algorithms",
   "Ab Sommer in Bayern: Das härteste Polizeigesetz seit 1945",
   "Hecktivism: How does digital networking translate into political organization on the ground?",
   "#Digitalcharta continued – Wir diskutieren weiter (Empfang)",
   "You gotta fight for your right to free knowledge!",
   "Update für deine Freiheit: Die neuen EU-Datenschutzregeln aus Sicht von Verbraucher*innen",
   "Teenage Kicks",
   "How To Lose A Country: The New Political Ice Age",
   "Opening Fireside Chat with Chelsea Manning",
   "How blogging is strengthening political coverage in Africa",
   "Global Digital Changemaker Meetup: Follow-up",
   "The Disability Revolution Will be Tweeted – Meetup",
   "Nach Nizza und München – Anatomie eines Shit-Tsunamis",
   "Identity management applications in international development",
   "Künstliche Intelligenz, Algorithmen und die Arbeit von Morgen",
   "Navigating the Future – HR als Wegbereiter der digitalen Transformation",
   "Uploadfilter: Nur die erste Schlacht von vielen",
   "Daten, Demagogen, Demokratie – was wir aus dem Skandal um Facebook und Cambridge Analytica lernen können",
   "The Web Women Want – How does tech fuel the feminist discourse worldwide?",
   "Eröffnungspanel: Die Revolution disst ihre Kinder – alte Linke, neue Rechte und das Internet",
   "#Europabrauchtdich! – Mobilisierung für die Europawahl 2019",
   "Freundeskreis Freiheit (im Netz) – Die freundliche Verweigerung",
   "Pop, rights?! Zwischen Netz und Politik",
   "The new kingmakers: How Silicon Valley created a new culture of celebrity",
   "Bürgerarbeit – Die Zukunft des Gemeinwohls",
   "Pop und Anti-Pop – Wie das Internet uns lehrte zu kämpfen. Und wofür.",
   "Diversity & the Fe:male Digital Footprint",
   "The Female Effect – Technology Through A Gender Lens",
   "Corporate Digital Responsibility: Welche Verantwortung haben wir als Unternehmen in der Digitalökonomie?",
   "The Political Tragedy of Data-Driven-Determinism",
   "#Digitalcharta continued – Wir präsentieren die überarbeitete Fassung 2018",
   "Perspectives from developing countries – It’s the End of the work as we know It (and I feel fine)!",
   "Klima-Fakt statt Klima-Fake",
   "Designing Tomorrows / 4 Futures Workshop",
   "SolarPunk and going Post-Post-Apocalyptic",
   "re:claim autonomy – Digitale Freiheitsrechte in der neuen Legislatur",
   "Technology and social responsibility",
   "The Present Is Now: Endlich wieder Spaß im Netz! (Creamspeak)",
   "Resilient Speculation",
   "Whose Future? Automation anxiety, ecological apocalypse, and the struggle for the future of labor",
   "Fighting Hunger with Digital Innovations",
   "Freie Daten-Vorfahrt oder juristische Notbremse? Statusupdate Netzneutralität",
   "Young Minds Shine Bright – Global Digital Changemaker Meetup",
   "Building a sustainable information ecosystem for human rights and democracy",
   "New Kids on the Blockchain: Jahresrückblick mit dem Bundesblock",
   "Gender ABC",
   "\"You know nothing, Laowai!\" Ein top secret Briefing zu Chinas Onlinekultur hinter der Great Firewall",
   "Commons-based Communities: Viable Alternatives to Digital Capitalism?",
   "Algorithmen: Zu Risiken und Nebenwirkungen – fragen Sie Ihren Informatiker",
   "Empower the people – Konkrete Ansätze für die digitale Arbeit der Zukunft",
   "The Future of Data for Development",
   "Fighting for Transparent Conditions For Consumers and Smart Devices",
   "Digital rights defenders under threat: Strategies to resist fear, surveillance and (self-) censorship",
   "Building a new life, one e-lesson at a time: refugees and online education",
   "Facts & Fiction: The Myth of German Microtargeting",
   "Taxation and leaks like Paradise Papers ... an endless story",
   "Unfassbare Internet-Geschichten und was dahinter steckt",
   "POP conventional policy making meet up: Networked European Democracy",
   "Disruptive Innovation and Democracy Meetup",
   "Bild getwittert -> Tatverdacht!",
   "Die Zahlen der Politik",
   "…And the Disability Revolution Will be Tweeted: How Twitter Has Impacted Disability Advocacy Worldwide",
   "Rechtsruck in Deutschland – Linksabbiegen (un)möglich?",
   "Why The Zombie Haunts The Cyborg – Unveiling The Inherent Racism of Transhumanism",
   "Critical Social Infrastructure: Responding to Attacks on National ID Systems",
   "Make the GDPR POP! – Reclaiming data rights through citizen education",
   "The Big Open: How do we make the open internet revolution irresistible?",
   "Technik im Körper: Seitenwechsel per Implantation",
   "Digitale Informationen für Geflüchtete gestalten",
   "Algorithmen und Künstliche Intelligenz: Wegweiser für Politik und Gesellschaft",
   "Hilfreich gegen Hass oder Anschlag auf die Meinungsfreiheit? Vier Monate NetzDG",
   "Burning out digital colonialism",
   "ÖRR: Offenes Gespräch unter Freunden",
   "Feministische Memes?! Eine Untersuchung von #metoo",
   "Us, too",
   "How Zero Net Neutrality Made Fake News More Potent",
   "Social Media Monitoring and how to build better Alternatives – Meetup",
   "Zivilcourage im Netz!",
   "Participative Cryptoeconomics — The Future Of Universal Income",
   "Gamified Control? China's Social Credit Systems",
   "Exploring standards for algorithmic transparency",
   "Entgeltgleichheit für Männer und Frauen – Ein Praxisbeispiel aus dem Journalismus",
   "Gemeinsam gegen Hate Speech Meetup",
   "Blockchain tokenization and the public infrastructure",
   "Wie können wir Digitalkompetenz bis ins hohe Alter sichern?",
   "#AfricaBlogging – How bloggers are taking over from traditional media",
   "PoP: Power of Patients – Wie Digital Health das Gesundheitswesen revolutioniert",
   "Vom Tod in der Netz-Familie",
   "Kinderrechte im/ins Netz! Lasst uns die Teilhabe von Kindern im Digitalen stärken",
   "OpenSCHUFA – Crowdsourcing algorithmic accountability",
   "Community Building: Machine Learning applied to Human Rights",
   "State of the Open",
   "Bist du ein Bot? Wie Automatisierung unsere Kommunikation verändert.",
   "Wohin mit der Informationsfreiheit in Deutschland?",
   "Queering the internet: A sociological analysis of queer online activism",
   "Wie Datenschutzbehörden wirklich ticken – aus dem Innenleben einer Aufsichtsbehörde",
   "#KeinerTwittertAllein – vom Platzenlassen von Filterbubbles und anderen Isolationen",
   "Beautiful Robots: Selling Automation to the Public",
   "The Fairwork Foundation: strategies for online platform work",
   "Die Pop-Karriere der deutschen Netzpolitik: Eine Erfolgsgeschichte?",
   "Machines in war – why we need to regulate Autonomous Weapon Systems",
   "Warum sind die Rechten so hip im Netz?",
   "No women, no web – Digital skills trainings in fragile contexts",
   "Data Clinic: Twitter data selfies & data portraits",
   "Wie man erfolgreich einen Geheimdienst verklagt",
   "Mehr Sichtbarkeit für Minderheiten: ohne uns kein \"wir\"!",
   "Building an Infrastructure for Transnational Discourse",
   "Civic & Tech: Open Government Jetzt!",
   "Die Teilung der Welt: Polarisierung ist Pop",
   "Breaking the 4th Dimension: Gamers as Forces for Social Good",
   "Soziopod Live: Pop & Popper – Was Geschichten im Netz mit Identität und Werten machen",
   "Blockchain: Digital Identities for Everyone?",
   "(Digital) Identity: The Haves and Have-Nots",
   "Polizeidatenbanken: Datenauskunft DIY (nicht nur) für Netzaktivistinnen",
   "1981 – Kraftwerk's Album Computerwelt und der NSA-Skandal",
   "The (accidental) developer in disputed territories",
   "E-Bracelets and the Digitization of the Pilgrimage to Mecca",
   "The Passing",
   "rp:USA Brainstorming Meet-up",
   "We are nature – An exploration from non-human perspectives",
   "Kunst & Protest: Meet up",
   "WOMEX – Can Blockchain Unchain Global Diversity?",
   "Preserving Heritage at Risk with Google Arts & Culture and CyArk",
   "When art meets technology: from Gigapixels to Machine Learning",
   "Empire of Oil Project Follow Up",
   "Spot on for the marginalized!",
   "Hunting high and low – Jens Balzer über den POP",
   "Designing Presence in Immersive Reality",
   "Machine listening: Applications of AI to Music",
   "Film Screening: The Cleaners – Die Digitale Müllabfuhr",
   "On Monstrosity and Visibility",
   "Access to Bodies: Ein Leitfaden für post-humane Computer und Körperanwendungen",
   "Menschen als Software-Erweiterungen",
   "Baut die Zukunftsskulptur zusammen mit Start Coding e.V. und Junior Lab",
   "Dein Ticket für die Ewigkeit!",
   "Cancel the Apocalypse Meetup",
   "Tales of Spatial Transformation: How to Mix Digital and Physical Without Destroying the World",
   "AI Music Composition in VR",
   "Towards the Internet of Musical Things",
   "Unboxing: Sound",
   "Der Innovationsfonds der Berliner Kulturverwaltung: Digitale Entwicklung im Kulturbereich",
   "Project Presentations: VR:RV & 	",
   "VR:RV|Stories We Tell",
   "Metall auf Metall, Kunstfreiheit & Urheberrechte",
   "Neue MusikmachDinge: Augmenting Creativity and Connectivity?",
   "Digitale Identität",
   "Pop ist wenn man dazu tanzen kann? – Literarische Stimmen zum Zustand des Pop",
   "Blockchain and Culture",
   "Performersion|The function of Touch Feedbacks in VR Without Haptic Mechanics",
   "Performersion|Geschichten außer Kontrolle – Storytelling ohne AutorInnen",
   "Live Nude Girls: Feminist Art & Sex Work in the Digital Age",
   "Theatre white space. Was Theater im Netz finden könnte",
   "We, the Data Workers: Challenging the future of labour",
   "Empire of Oil / From Documentary to Performing Arts to VR",
   "Wir zeichnen Pop! – Collaborative Sketching",
   "Volumetric VR – Bringing VR to a new level",
   "Building Fearless Futures",
   "DIY Personal Mini Cloud",
   "Kunst & Protest: 1000 GESTALTEN auf dem G20-Gipfel",
   "Brains are the new wave",
   "VR-Meetup: Kunst, Kultur und immersive Medienformen",
   "\"Smart Lies – alles smart?\" – eine Lesung",
   "Let’s make Drawbots from Junk!",
   "Reading #metoo: eine analytische Sexismus-Lesung von Weltliteratur bis zu Online-Kommentaren",
   "Kreatives Coding Spices Up Your Life",
   "KIBA – Die Künstliche-Intelligenz-Berufs-Agentur",
   "europeanpa55port.com",
   "BINGO – Harmloser Spaß oder gefährlicher Extremsport?",
   "ShePop? Weibliche Körper in der Popmusik zwischen Subjekt und Objekt",
   "(Insane in the) brain drain: Mensch-Maschine-Schnittstellen, KI und kreative Prozesse",
   "Die Internet-Verlegerinnen",
   "Wer umschreibt, bleibt!",
   "Sheer (Pixelated) Madness? Mental Health in Video Games",
   "Impulsvortrag: Marketing bei Coca-Cola",
   "Digital Marketing Trends 2020",
   "Digital Platforms – The Future of Finance",
   "Financial Institutions and Fintechs in Germany, the Near and Middle East",
   "Impulse Food: Slowfood fast, Metzger Marketing und soziale Nachhaltigkeit",
   "Digitalisierung in der Gastronomie",
   "Slowfood fast – Technologie pro Entschleunigung.",
   "Modernes Metzger Marketing mit Social Media.",
   "Die Zukunft des Lieferessens: Wie Ghost-Restaurants klassische Restaurants ersetzen",
   "Eine gute Zukunft der Food-Branche: Ein Vorschlag wie wir ohne Illusion unser Nahrungssystem umkrempeln können.",
   "Snackable Content entlang der Customer Journey",
   "Augmented Reality – Reasons why AR will be the next battleground",
   "I run VR you – eine Erfolgsgeschichte für Mensch und Marke",
   "Best Case Influencer Marketing",
   "Data Security in the Scope of Distributed Ledger Technology",
   "Decentral Identity Management on the Blockchain",
   "Financial Health: What is it? Why is it important? What does it mean for companies, communities and individuals?",
   "Impulse Weiterdenken: Roboter, Sprachassistenten & mehr",
   "Wer liefert uns künftig die Ware? Die Drohne oder der Roboter?",
   "My Enso, Share foods & sensape: Startups mit neuen Impulsen für den Handel",
   "Reinventing Retail: Elf spannende Handelsinnovationen aus China, die Sie unbedingt kennen sollten",
   "Digitalisierung kann man nicht delegieren! Digitale Transformation ist Chefsache",
   "StartUp AsiaBerlin: Fostering Startup Ecosystems through International Cooperation",
   "Building Cooperative Alternatives for the Digital Economy",
   "Eine mögliche Zukunft für Innovation – Asset-based Co-Innovation",
   "Künstliche Intelligenz und die Zukunft des Marketing",
   "Envisioning a deeply connected international community network",
   "Startups and Founder Culture in India and Germany – The Journalists Perspective",
   "Agile Arbeitsweisen erlebbar gemacht!",
   "Von Bots und Boten",
   "The Future of Work: Will Robots and Automation Destroy or Save Us?",
   "Blockchain and media industries – A Canadian perspective",
   "Activating Local Networks Meetup",
   "Werbung auf den Leib geschneidert – KI in Unternehmen, personalisiertes Marketing und Datenschutz",
   "Künstliche Intelligenz im E-Commerce – Aktuelle & zukünftige Anwendungsbereiche",
   "Equitable Pioneers for the Digital Economy",
   "Digital Marketing Meetup",
   "Women in Finance & Blockchain Meetup",
   "Innovation labs in corporates",
   "Das knallharte und unglaublich kämpferische Interview",
   "It takes two to tango – How we partner with start-ups turning digital customer experience emotional",
   "Virtuelle Assistenten: Best Buddies oder \"Big brother is watching you\"?",
   "The LAB Game – How to create a venture",
   "Working at the lab",
   "Always connected – what´s next?",
   "Automatisierte Giganten: \"Kehrwoche\" in Reih' und Glied",
   "#hackingwork: Keine Manager, keine Überstunden und trotzdem was schaffen? So klappt Selbstorganisation als Unternehmen",
   "Generation Z: Wie Medien & Marketing im Zeitalter der Social Natives funktionieren",
   "tip-me.org – Das globale Trinkgeld",
   "The Krypto Economy: Beyond the Bitcoin Bubble",
   "Global Networks for Sustainable Local Manufacturing: Join the MakerNet Alliance",
   "Braucht das Silicon Valley eine Frauenquote?",
   "Private Vice, Public Virtue: Can you ever do Do Business and Be Good?",
   "Blockchain: a disruptive technology for global economic inclusion?",
   "Die Tragödie der Digitalisierung in Deutschland am Beispiel des besonderen elektronischen Anwaltspostfachs beA",
   "Kernkompetenz: durchwurschteln!",
   "Please do not disturb! Algorithmen bei der Arbeit",
   "Usability Testessen",
   "Surviving Social Media In The Workplace: A Kit",
   "Work fiction: Neue Arbeitszeitgestaltung in 2030+",
   "Digital Farming 1980 – 2050",
   "Startup Ecosystems Worldwide",
   "Digital Africa",
   "Die Zukunft ist müllfrei!",
   "Build your future with LEGO",
   "Smart Contracts auf der Blockchain",
   "Online-Tracking hinter den Kulissen – was wirklich mit unseren Daten geschieht",
   "German Mittelstand -Hidden Innovation Champions?",
   "Moneybots tragen keinen Schlips: Vincent Viola und der automatisierte Finanz-Cyberspace",
   "Digi-Tech-Edu-Art Projekt f. d. ländl. Raum (1)",
   "Digi-Tech-Edu-Art Projekt f. d. ländl. Raum (3)",
   "Digi-Tech-Edu-Art Projekt f. d. ländl. Raum (2)",
   "Dude, Where’s My Autonomous Vehicle?",
   "Building Open Lights for wheelchair users",
   "Mobilität in der dritten Dimension",
   "Im F.L.O.W. – Stau war gestern",
   "Shaping the future city – how connected car services make your life easier.",
   "Von Autos zu Einhörnern – Offene Daten, DYI Verkehrskamera und ein Online-Mini-Game im Namen der urbanen Mobilität",
   "IONITY: Connecting Europe with high power charging",
   "Einfach Parken ist zu wenig – Innovative Services rund um das parkende Auto",
   "Wegweiser durch den Barrieredschungel? WheelPilot!",
   "Meetup: Shared on demand: Bringt die Digitalisierung das Ende des Privatautos?",
   "Shared on demand: Bringt die Digitalisierung das Ende des Privatautos?",
   "Wie Uber, Didi & Co die Mobilität der Zukunft beeinflussen",
   "Do you want a Blockchain or do you really need it?",
   "Music, Data and the City: Towards Smart Music Cities",
   "Die Verkehrswende selber machen. Lastenrad-Sharing",
   "Deine Stadt ist nicht meine Stadt? Übers Leben mit Unternehmen, Robotern und anderen Menschen",
   "Zukunft in Stadt und Dorf: mit virtueller Vernetzung eine Arbeitswelt für alle",
   "Request Denied: Designing for Consent in Data Collection",
   "Smart Cities, grüner Kapitalismus und die Zukunft der Mobilität",
   "Tech-Firmen machen Stadt – Was heißt das für Berlin?",
   "Fabmobil – ein fahrendes Kunst- und Zukunftslabor für ländliche Räume",
   "Das digitale Paradoxon – fallen wir wieder hinter das Zeitalter der Aufklärung zurück?",
   "Why & How To Hack Cities For Sustainability"
];